name: mantohtml
version: 2022.1005
summary: Man page to HTML converter
description: |
  mantohtml is a man page to HTML conversion program.  It supports all of the
  common man/roff macros and can combine multiple man pages in a single HTML
  output file.

confinement: strict

grade: stable

icon: mantohtml-128.png

apps:
    mantohtml:
        command: bin/mantohtml
        plugs: [home]

parts:
    main:
        plugin: make
        source: .
        make-install-var: prefix
